### PR TITLE
Add Role-Based Access Control mechanism

### PR DESCRIPTION
**Pull request by chuckremes**
Right now there is no permission control within a bot. All users can run all commands by default. For larger Slack teams this can cause problems where team members do work outside of their role.

This PR provides a simple Role-Based Access Control mechanism. By default it uses a blacklist mechanism (called the DenyList). When a user is added to a group and a command is also associated with that group, the user will be DENIED access to the named command. For backward compatibility (all users can run all commands) this is the DEFAULT mechanism.

A second mechanism implementing a whitelist (named AllowList) can also be enabled. When in this mode, all users are DENIED running any commands. To run a command, a user must be explicitly added to a group and a command must also be registered with that group. When a command event is received, if the user matches the command then they are permitted to execute it. This is a much safer mode for large teams.

### CODE REVIEW

**Comment by dblock** [comment]
I think it's useful, but stepping back a little wouldn't we want to enable role based access with third party gems? Like cancan for example?

**Comment by chuckremes** [comment]
Interesting idea that I will explore. It might make sense to try and "copy" the `cancan` API and implement it here as a first draft. Then start to add support for that gem (or others) in subsequent revisions. I'll think on it today/tomorrow.

**Comment by chuckremes** [comment]
I'm spiking something out right now but it isn't going very well. :(

The `cancancan` gem is reliant upon quite a few Rails-specific classes to do its meta-programming magic. Also, this is really only feasible for those who want to use the new MVC "sugar." If they just use the current `command` interface then `cancancan` won't work for them at all (whereas my solution above does). 

Anyway, by day end I should know if this is workable or not. I'll report back.

**Comment by dblock** [comment]
There're probably other libraries like cancan. Another option is to make a separate library that lives on top of this, this forces us to have a much clearer interface.

**Comment by chuckremes** [comment]
@dblock I think I'll move forward with using a separate library that works in conjunction with `slack-ruby-bot`. I will close this PR and open a new one that will propose certain API changes to the `Command::Base` class so we can easily hook in a permission/authorization check.

**Comment by dblock** [comment]
Also https://github.com/Fingertips/authorization-san we use it in some projects.

**Pull request closed without merging**
