### PR TITLE
initial layout for simple pluggable security system on commands

### PR DESCRIPTION
**Pull request by chuckremes**
This PR isn't meant to be accepted right away "as is." Its purpose is for discussing how to add an authorization mechanism to `slack-ruby-bot`.

I played with multiple approaches before landing on this one. This is actually the simplest and most flexible of my attempts. It allows a programmer to register a Proc/proc/lambda with the framework to provide a true/false answer on whether or not a command can be run. Multiple "authorizers" can be registered. All must return true for the command to be permitted; if any return false, it's denied.

I like this approach because it provides maximum flexibility. The code passed in to the security class only has to respond to `call`, accept 3 args, and return true/false. This allows for arbitrary complexity on the part of the actual authorizer.

The authorizer could look up permissions in a database, load them from a hash, or just randomly permit/deny. It can use any of the data available in the `client`, `data`, and `match` objects to make its decision.

By default, if no authorizers are registered then the `command` is permitted.

Anyway, I'd like to discuss this idea here and will see if @digitalextremist wants to chime in too since we'll both be using this code or something similar on our non-hobby projects.

### CODE REVIEW

**Comment by chuckremes** [comment]
Ping to @dblock in case he isn't auto-notified of this PR.

**Comment by chuckremes** [comment]
Yes, @dblock that is a reasonable compromise. I'll adjust the PR so that it just has a `permitted?` method that returns true. I'll also update the docs to describe its purpose.

Thanks for the code review.

**Comment by chuckremes** [comment]
@dblock Per our conversation above, I made the suggested change and documented it. I also squashed all of the commits to a single commit. Please review and merge at your convenience.

**Comment by dblock** [comment]
Great, this does need a spec and it's good to go.

**Comment by dblock** [comment]
Great, merged.

**Pull request merged**
