### PR TITLE
Add TargetRubyVersion for rubocop

### PR DESCRIPTION
**Pull request by wasabigeek**
~Ran `bundle exec rubocop --auto-correct`~

~I could try to update the CI to use the repo's rubocop files in addition to the shared repo, though I'm not as familiar with Travis.~

Add the TargetRubyVersion so I don't embarrass myself in the future.

### CODE REVIEW

**Comment by dblock** [comment]
We only test >= 2.3, is this still correct? 

`rubocop -a ; rubocop --auto-gen-config` is my workflow

**Comment by wasabigeek** [comment]
Will try that command later, previously I also tried 2.3 but it raised a lot of linting errors. The travis logs suggested that 2.2 was still being used for Rubocop

**Comment by dblock** [comment]
I guess my naive question is why would I merge this?

**Comment by wasabigeek** [comment]
Sure - it's slightly selfish, but my linter automatically marked a lot of issues, I guess because the default target ruby isn't 2.2. As a contributor, it wasn't clear if I should fix them or leave them.

**Comment by dblock** [comment]
Let's have a target version, I'll merge it.

**Pull request merged**
