### PR TITLE
Exposing SlackRubyBot::CommandsHelper.find_command_help_attrs

### PR DESCRIPTION
**Pull request by alexagranov**
@dblock - per #172

### CODE REVIEW

**Comment by dblock** [comment]
Merged. 

I wonder whether we should rename this method and refactor this a bit now that we're trying to expose this publicly.

* `CommandsHelper` is a confusing utility name, because it's really about `Help`, so maybe it should just be `CommandsHelp`?
*  `CommandsHelper#find_command_help_attrs(name)` could be just `Help#get(name)`.
* `#capture_help` should be private and executed lazily when someone tries to get anything from `Commands` the first time.
* `commands_help_attrs` becomes an internal `attrs`

Thoughts?

**Comment by alexagranov** [comment]
✅ ✅ ✅  & ✅ 
spot on, would really simplify the interface.

**Comment by dblock** [comment]
Looking forward to a PR :)

**Comment by alexagranov** [comment]
haha ok, will put on my list!

**Pull request merged**
