### PR TITLE
Ordered commands

### PR DESCRIPTION
**Pull request by gconklin**
My attempt at addressing #75 -- probably not the most ruby way to do it but is working for my purposes; comments welcome.

### CODE REVIEW

**Comment by dblock** [comment]
It's an interesting solution. However I think it would be simpler to keep a global list of commands when `inherited` and not rely on dynamically accessing `SlackRubyBot::Commands::Base.descendants`.

I would start by writing a test :)

**Comment by gconklin** [comment]
I am king of Interesting Solutions(tm).  I will start by writing a test! as i should have.

**Comment by dblock** [comment]
Just noticing this @gconklin, merging.

**Comment by dblock** [comment]
This caused https://github.com/slack-ruby/slack-ruby-bot/issues/113. I fixed it in a straightforward way in #114, but I am not sure it's the right way. Would appreciate a second pair of eyes from @gconklin, please.

**Comment by gconklin** [comment]
I spent some time looking. It does clearly fix #113, but after a bit of Googling, I'm still not entirely sure why `@command_classes` is different from `SlackRubyBot::Commands::Base.command_classes` in the context of `self`. I expect it's my failure to grasp class instance variables, and that `@command_classes` is different when the test bot inherits from `SlackRubyBot::Bot` as opposed to a command directly inheriting from `SlackRubyBot::Commands::Base`

**Comment by dblock** [comment]
I couldn't figure it out either, no worries.

**Pull request merged**
